# Generated by Django 4.0.5 on 2022-06-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Institute_name',
                'verbose_name_plural': 'Institute_name_s',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(blank=True, max_length=128, null=True)),
                ('numbers', models.CharField(blank=True, max_length=128, null=True)),
                ('deposit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Sponsor_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.IntegerField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Metsenatapp.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor_deposit',
                'verbose_name_plural': 'Sponsor_deposit',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('numbers', models.CharField(blank=True, max_length=128, null=True)),
                ('deposit_Student', models.IntegerField(blank=True, default=-1300, null=True)),
                ('student_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Magistracy', 'Magistracy')], max_length=64)),
                ('institute_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Metsenatapp.institute_name')),
                ('sponsor_deposit', models.ManyToManyField(blank=True, null=True, to='Metsenatapp.sponsor_deposit')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
