# Generated by Django 4.0.5 on 2022-06-13 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metsenatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='deposit_Student',
            field=models.IntegerField(blank=True, default=1300, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='у студента уже дастаточна денег')]),
        ),
    ]
